#!/bin/sh

echo "Checking if user snort exists:"
id snort
RET=$?
if [ $RET -ne 0 ]; then
	echo "Creating the user snort, in the group snort."
	groupadd snort
	sudo useradd -g snort snort
else
	echo "It exists. No need to create it"
fi

if [ ! -f /etc/snowman/snowman-client.config ]; then
	cp /etc/snowman/snowman-client.config.template /etc/snowman/snowman-client.config
	echo "A sample-configurationfile is added to /etc/snowman/snowman-client.config"
fi

chown snort:snort /etc/snowman/snowman-client.config
chmod 644 /etc/snowman/snowman-client.config

mkdir -p /var/run/snowman/
chown snort:snort /var/run/snowman/

mkdir -p /var/snowman-client
chown snort:snort /var/snowman-client

touch /var/log/snowman-client.log
chown snort:snort /var/log/snowman-client.log

exit 0
